module Epom
  class LimitCounter
    TOTAL_IMPRESSIONS = 'TOTAL_IMPRESSIONS'
    TOTAL_CLICKS = 'TOTAL_CLICKS'
    TOTAL_REVENUE = 'TOTAL_REVENUE'
    DAILY_IMPRESSIONS = 'DAILY_IMPRESSIONS'
    DAILY_CLICKS = 'DAILY_CLICKS'
    DAILY_REVENUE = 'DAILY_REVENUE'
  end
end